# Generated by Django 5.2.3 on 2025-07-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libros", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libro",
            name="imagen",
            field=models.ImageField(
                blank=True,
                default="libros/libro_default.jpg",
                null=True,
                upload_to="libros",
            ),
        ),
    ]
